### ISSUE TITLE
[FR] Implement a scheduler for scraper

### ISSUE THREAD

**Issue by diegov-au** [mlapaglia/OpenAlprWebhookProcessor#107]
Great program, thanks for spending time to create this. I was wondering whether it would be possible for you to implement a scheduler function for the scraper. For example setting the scraper to run every minute. This would allow us to bypass the use of the webhook and keep incoming ports closed.

Thanks.

**Comment by mlapaglia** [comment]
this has been implemented https://github.com/mlapaglia/OpenAlprWebhookProcessor/pull/110

**Comment by mlapaglia** [comment]
![image](https://github.com/mlapaglia/OpenAlprWebhookProcessor/assets/4184746/e70dc337-2c60-4e4a-a7a8-bb960ae18ec7)
